apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: integrationtest-tcp
  name: integrationtest-tcp
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 6550
  selector:
    io.kompose.service: integrationtest
  type: LoadBalancer
status:
  loadBalancer: {}
