name: Docker Image CI

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: adgscicd.azurecr.io
        username: ${{ secrets.ACR_SPID }}
        password: ${{ secrets.ACR_SPPWD }}        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -f ./IntegrationTest/IntegrationTest/Dockerfile  ./IntegrationTest --tag adgscicd.azurecr.io/demoapi_autobuild:$(date +%s) --tag adgscicd.azurecr.io/demoapi_autobuild:latest
        docker push adgscicd.azurecr.io/demoapi_autobuild:latest
        
      
